version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: azurian
      POSTGRES_USER: yme
      POSTGRES_PASSWORD: yme
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: